apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: product-api
  namespace: app
  annotations:
    cert-manager.io/cluster-issuer: zerossl
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: product-api-tls
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /api/products
            pathType: Prefix
            backend:
              service:
                name: product-api
                port:
                  number: 80

